server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;

        # Kill caching for index.html
        if ($uri = "/index.html") {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }
    }

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
